### ISSUE TITLE
Old PR #449: Load all sites from file & block general paywall-scripts & add Caixin Global/Scribd/Tech in Asia/Newcastle Herald/The Athletic & fix Economist/Nrc.nl/MIT Tech Review/Dn.se/photos AFR/Globe and Mail/Handelsblatt & remove Dynamed

### ISSUE THREAD

**Issue by magnolia1234** [magnolia1234/bypass-paywalls-chrome-clean#1]
Load all sites (+ custom) from json-file (sites.json).
Less maintenance because defaultSites are obsolete (in background/options.js).
Domains by default are added to allow/remove_cookies (just a few allow_cookies entries are left).
Custom sites for smaller sites and quick updates (json-file read directly from GitHub repo).
Less familiar sites currently in BP could also be transfered to the custom list.

Block general paywall-scripts (also in options)
Block paywall-scripts like TinyPass/Piano (Economist, Spectator, Foreign Policy etc.) and Poool.fr (Challenges.fr).
New seperate option for these scripts (or in future by default?).
PS can also be blocked by uBlock Origin with Fanboy's Enhanced Trackers List

Allow cookies for sites with Googlebot user-agent.
Also sort Googlebot-sites (double entries).

Add Caixin Global.
Already in Firefox add-on.

Add Tech in Asia @winstonma

Add Newcastle Herald
Already in Firefox add-on (old domain)

Fix Economist (Javascript/cookies); mobile menu is no longer working.

Fix Nrc.nl (paywall).
New paywall-overlay for specific articles (test?).

Fix Dagens Nyheter (dn.se)
Hold on to edition-cookie (by only dropping id-cookie).

Fix Toronto Star (enable Javascript)
Fix Australian Financial Review (enable Javascript/photos)

Fix Globe and Mail (enable Javascript/photos, no video and photo gallery though)
Update: clear in-memory cache for Webrequest to work correctly (block or not block specific G&B-Javascript).

Fix Handelsblatt (Googlebot)

Fix LeParisien.fr (block TinyPass paywall).
Fix LesEchos.fr (block TinyPass paywall).

From @iscreamcoke
* Add Scribd (unblur text of documents)
* Add The Athletic
* Fix TheTimes.co.uk (remove subscription-block)
* Fix for MIT Tech Review (click the buttons to expand article and close banner)
* Fix Bloomberg, Asia Nikkei & Haaretz.com (banners)
* Refresh the current tab after saving options
* Deprecate Dynamed
* Fix Hbr.org banner

Readme.md:
* Installation instructions for Yandex browser on Android
* Table of contents
* Instruction for Fanboy's Enhanced Trackers List (block paywall-scripts)

**Comment by iscreamcoke** [comment]
You could merge the Chrome and Firefox repos of BP if you have the will

**Comment by iscreamcoke** [comment]
You could merge the Chrome and Firefox repos of BP-clean if you have the will

**Comment by iscreamcoke** [comment]
btw I've been working on a uBlock list of elements to be blocked in order to lighten customScript.js

**Comment by magnolia1234** [comment]
The sky is the limit ;-)

**Comment by iscreamcoke** [comment]
btw there are errors when installing your last master.zip

**Comment by magnolia1234** [comment]
Still? I removed the GA-script (background) after removing the rights (manifest).

**Comment by iscreamcoke** [comment]
In manifest.json:

```
Could not load extension icon 'bypass.png'.
Could not load manifest.
```

and

`'content_security_policy': CSP directive 'object-src' must be specified (either explicitly, or implicitly via 'default-src') and must whitelist only secure resources.`

**Comment by iscreamcoke** [comment]
I would also suggest a better name for your new project, maybe the pun BreakNews or BreakingNews.

**Comment by magnolia1234** [comment]
Added bypass.png again.
No CSP-error here though.

**Comment by magnolia1234** [comment]
Thanks, fixed CSP-error.

**Comment by iscreamcoke** [comment]
Nice work and improvements - Would you want a clean and simple landing page for the extension?

**Comment by iscreamcoke** [comment]
btw, here's an except of the uBlock list I've been building. Would you be interested in this solution to lighten the work on contentScript.js?

```
!
! COSMETIC NEWS
!
! visit https://github.com/magnolia1234/bypass-paywalls-chrome-clean
!
! subscribing banners
www.ft.com##.o-message--marketing__anon-subscribe
www.leparisien.fr###\30 fcvEBwhbrC
www.lemonde.fr##.message__offre
www.nytimes.com##.css-xv1bll
www.haaretz.com##.h-hidden--to-l.h-hide-paying
www.repubblica.it###latest-subscription-message
www.irishtimes.com##.slideFromLeft.floating_tab > .gtm-event
www.irishtimes.com##.sub-prompt.span4
www.irishtimes.com##.article_footer_subscribe
www.valeursactuelles.com##.abonnement-va
!
! ad_blocks not fully removed by uBlock
!
www.lesechos.fr##.fESsUe
www.lesechos.fr##.fAcjgi
www.lesechos.fr##.qxebl
www.wsj.com###wrapper-AD_PUSH
www.thetimes.co.uk###ad-article-inline
```

**Comment by iscreamcoke** [comment]
In this uBlock list, we could move all 'non-vital' removeDomElements of contentScript.js (those not necessary to bypass the paywall)

**Comment by magnolia1234** [comment]
You want to use this list in BP or give instruction to add it to uBlock Origin or other adblocker?

**Comment by iscreamcoke** [comment]
If possible, we can call it from one of our js files. If it's too time-consuming, we add the instructions for subscribing to the adblock list in the readme.

**Comment by magnolia1234** [comment]
You can always host it on GitHub, we'll see.
Btw did you check issue 4?

**Comment by iscreamcoke** [comment]
Yes absolutely, I'll host it on GitHub when I have more urls. For the moment, I only did 10–20% of the websites supported by BP and haven't import anything from contentScript.js yet
