### ISSUE TITLE
Microsoft Edge Beta - Error Loading Extension

### ISSUE THREAD

**Issue by Skates1616** [magnolia1234/bypass-paywalls-chrome-clean#11]
While trying to install the addon within the latest Edge beta, I get the following error:

![image](https://user-images.githubusercontent.com/23196661/72754582-d77de100-3b8d-11ea-94dd-7918dcd3e448.png)

I tried installing it by dragging over the .crx to the extensions screen.

**Comment by Skates1616** [comment]
I think I found the cause, its discussed here:

https://support.google.com/chrome/thread/7757612?hl=en&msgid=12927643

**Comment by magnolia1234** [comment]
Dragging a local crx-file worked indeed fine for me.
Btw there was an official release of Edge (Chromium) just a few days ago.

**Comment by Skates1616** [comment]
I am dragging it over and have developer mode selected, still the same error.

I am using the following version:

![image](https://user-images.githubusercontent.com/23196661/72755438-1a40b880-3b90-11ea-92f3-1a111da4f215.png)

**Comment by magnolia1234** [comment]
Install from unpacked folder (master zip-version).

**Comment by Skates1616** [comment]
I was able to install using the Load Unpacked button.

Dragging and dropping the folder or the CRX gave me the error.

**Comment by iscreamcoke** [comment]
Dragging the CRX gives me the same error on Mac now (v79.0.309.68). Try updating Edge and dropping the crx @magnolia1234?

Let's see if we if we merge Chrome and Edge instructions, it'll work for everyone.

**Comment by magnolia1234** [comment]
Fixed already and added Yandex to Chromium browsers.

**Comment by iscreamcoke** [comment]
Great could you just move `(Windows/MacOS/Linux)` at the end of the line, there're mobile versions of Edge too (obviously not Chromium-based on iOs but let's think user-first ;-))

**Comment by magnolia1234** [comment]
Yes, but they don't support extensions ...

**Comment by iscreamcoke** [comment]
yes I know, I just feared that putting `(Windows/MacOS/Linux)` at the beginning would imply it's not the case for Edge. Although if you think it's clear enough like that, then don't change it

**Comment by magnolia1234** [comment]
Nobody reads a manual ;-)

**Comment by iscreamcoke** [comment]
yes there wouldn't be any work left for the support (aka github issues) otherwise ;-)

**Comment by magnolia1234** [comment]
Seems obvious to me, but add it to your PR if you like.

**Comment by iscreamcoke** [comment]
the priority for now is to move the thousand of users from the 'old' extension to the new one ;-) we'll see later if we're flowed under 'Edge issues'

**Comment by iscreamcoke** [comment]
the priority for now is to move the thousands of users from the 'old' extension to the new one* ;-) we'll see later if we're flowed under 'Edge issues'

*unfortunately no news of Adam, I hope everything's okey of him

**Comment by iscreamcoke** [comment]
the priority for now is to move the thousands of users from the 'old' extension to the new one* ;-) we'll see later if we're flowed under 'Edge issues'

*unfortunately no news of Adam, I hope everything's okay for him

**Comment by magnolia1234** [comment]
Flowed?
No worries, Adam (orcollaborator) removed my new release issue in half a hour ...

**Comment by iscreamcoke** [comment]
> Flowed?

French deformation, I meant overflowed/overspoeld/débordé

> No worries, Adam (orcollaborator) removed my new release issue in half a hour ...

which new release? Well we did nothing wrong, we were proposing PRs, he didn't answer for a month and we forked his MIT-licensed project (which had been mainly depending on our PRs since last October anyway)

**Comment by magnolia1234** [comment]
The issue #446 that got removed on the 12th of january (break-free-time).

**Comment by iscreamcoke** [comment]
The Firefox issues page of BP is a mess indeed, I've just taken a look at it

**Comment by iscreamcoke** [comment]
could you also share the ModHeader profiles you have created?

**Comment by magnolia1234** [comment]
> The Firefox issues page of BP is a mess indeed, I've just taken a look at it

Relevancy?

**Comment by iscreamcoke** [comment]
> Relevancy?

it wouldn't be such a mess had he kept your link to the new repo

**Comment by magnolia1234** [comment]
Still, Firefox issues and Chrome extension ...?

**Comment by magnolia1234** [comment]
> could you also share the ModHeader profiles you have created?

You can use the referer and user-agent from BP.
ModHeader has default entries for the names.

**Comment by iscreamcoke** [comment]
> Still, Firefox issues and Chrome extension ...?

That's a misunderstanding, I thought you were talking about deleted issue #446 in Firefox repo

**Comment by iscreamcoke** [comment]
> You can use the referer and user-agent from BP.

I have an 'access denied' on The Athletic with the profile.

<img width="1254" alt="Screen Shot 2020-01-25 at 09 58 57" src="https://user-images.githubusercontent.com/17458353/73118794-60fc2d00-3f59-11ea-8982-194c50b4addf.png">

**Comment by iscreamcoke** [comment]
ps: @magnolia1234 dragging the extension's folder doesn't work on Edge MacOS (it just displays the folder's files). You have to click 'load unpacked', then choose the extension's folder. Can you confirm this also works on Windows?

**Comment by magnolia1234** [comment]
> > You can use the referer and user-agent from BP.
> 
> I have an 'access denied' on The Athletic with the profile.

Copy user-agent from BP: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
But indeed you also need requestheader X-Forwarded-For for it to work on The Athletic.

**Comment by magnolia1234** [comment]
> ps dragging the extension's folder doesn't work on Edge MacOS (it just displays the folder's files). You have to click 'load unpacked', then choose the extension's folder. Can you confirm this also works on Windows?

I never dragged the folder anyway, but 'load unpacked folder' works just fine on Win10.
