### ISSUE TITLE
The Examiner issue

### ISSUE THREAD

**Issue by iscreamcoke** [magnolia1234/bypass-paywalls-chrome-clean#17]
Blocking piano.io breaks any article on examiner.com.au, even the free ones. Consider making a whitelist for the global blocking of piano.io.

It must override uBlock's settings as piano.io is blocked in a uBlock default list ("uBlock filters – Unbreak")

sample: https://www.examiner.com.au/story/6598478/after-66-years-she-did-it/?cs=12

**Comment by magnolia1234** [comment]
The Examiner (like Nwcastle Herald) has a 2nd layer of protection.
If you like you can add the specific lines in contentscript.js (subscriber-truncate/hider) though.
