### ISSUE TITLE
Cannot enable 1.6.1.2

### ISSUE THREAD

**Issue by jcarrollpe** [magnolia1234/bypass-paywalls-chrome-clean#2]
Doesn't pass web store "This extension is not listed in the Chrome Web Store and may have been added without your knowledge." Used .CRX   did not see master. Non-clean master would not load either. Error "could not load extension icon "bypass png" could not load extension. Chrome ver. 80.

**Comment by jcarrollpe** [comment]
Clean 1.6.1.2 master zip loads and is enabled. Testing now

**Comment by magnolia1234** [comment]
Try crx-release v1.6.1.3?

**Comment by jcarrollpe** [comment]
Master zip on 1.6.1.3 will not enable due to web store CHECK. Previous versions worked around this check.  Did not see  1.6.1.3 .CRX. Going back to 1.6.1.2. Congrats on your "clean break"!

**Comment by jcarrollpe** [comment]
Excellent. Thanks again for the clean break and seemingly a ton of time & effort...  v1.6.1.3 now running on (master.zip): 

- Desktop Chrome Beta : Version 80.0.3987.42 (Official Build) beta (64-bit) 
- Desktop Brave Dev: Version 1.4.57 Chromium: 79.0.3945.117 (Official Build) dev (64-bit)
- Chromebook (Rammus) Chrome OS (Beta): Version 80.0.3987.39
