### ISSUE TITLE
Enhancement: New request- UpstreamOnline

### ISSUE THREAD

**Issue by jcarrollpe** [magnolia1234/bypass-paywalls-chrome-clean#20]
https://www.upstreamonline.com/field-development/petrobras-mulls-mero-3-fpso-tender-delay/2-1-744335

Followed your instructions in Readme.md.  Also turned off uBlock and refreshed. no luck. 

![upstream](https://user-images.githubusercontent.com/59202876/73141657-2f17c300-404c-11ea-9345-1c8c140bf627.JPG)

**Comment by magnolia1234** [comment]
Looks like a hard paywall (subscription-only).
