### ISSUE TITLE
site request: Telerama

### ISSUE THREAD

**Issue by Crrrrrrr** [magnolia1234/bypass-paywalls-chrome-clean#21]
Any chance you can break the paywall on this french newspaper? https://telerama.fr

Here's an article behind a paywall: https://www.telerama.fr/television/dark-blue-sur-prime-video-une-descente-aux-enfers-dans-le-los-angeles-de-james-ellroy,n6595253.php

**Comment by llacb47** [comment]
Hard paywall, probably not

**Comment by magnolia1234** [comment]
Looks like a hard paywall indeed (subscription-only).

**Comment by iscreamcoke** [comment]
Yes, it looks like a hard paywall. None of our workarounds works.

We'll keep you in touch here if we find a solution though ;)

**Comment by iscreamcoke** [comment]
If you want to download the pdf version of French newspapers, use https://ww2.french-bookys.com

**Comment by Crrrrrrr** [comment]
That's too bad. I was hoping they were using the same paywall as LeMonde.fr (they're owned by the same company).

**Comment by iscreamcoke** [comment]
@Crrrrrrr yes newspapers can belong to the same company and use different paywall methods.

I'm going to add more French-speaking newspapers in the coming days. Don't hesitate to create a request if you have a specific website in mind.

**Comment by iscreamcoke** [comment]
@Crrrrrrr yes newspapers can belong to the same company and use different paywall methods.

I'm going to add more French-speaking newspapers in the coming days. Don't hesitate to create a request if you have a specific website in mind.

Use the link I've provided for 'unbypassable' paywalls like L'Équipe or Télérama.
