### ISSUE TITLE
Site request: www.theinformation.com

### ISSUE THREAD

**Issue by vic958420** [magnolia1234/bypass-paywalls-chrome-clean#23]
Site can by bypassed in incognito mode with referer set to Facebook. Example article: https://www.theinformation.com/articles/google-developing-new-unified-communications-app-for-businesses

**Comment by iscreamcoke** [comment]
Hi @vic958420. Just based on the information you provided, I've done a quick try of incognito mode with referrer set to Facebook with no success.

<img width="1251" alt="Screen Shot 2020-01-29 at 22 10 04" src="https://user-images.githubusercontent.com/17458353/73397699-5f798e80-42e4-11ea-9100-aaba2c2ac3f5.png">

Don't worry though, we're going to take a closer at it and introduce a workaround as soon as possible ;-)

**Comment by magnolia1234** [comment]
A Facebook post doesn't bypass the paywall though.
