### ISSUE TITLE
WSJ blogs issue

### ISSUE THREAD

**Issue by severing77** [magnolia1234/bypass-paywalls-chrome-clean#24]
The WSJ blogs are unavailable on Firefox android, you fixed it on Chrome extension.

I didnt check for Firefox PC version though.

**Comment by magnolia1234** [comment]
Well actually fixed, but not yet released in a new version (see post-release commits).

**Comment by severing77** [comment]
OK. Thank you for your feedback. Also, it seems that Ublock Plus Adblocker is removed from the Chrome Webstore, so Chromium browsing apps such as Yandex don't have adblocker support for your extension anymore. 

https://chrome.google.com/webstore/detail/ublock-plus-adblocker/oofnbdifeelbaidfgpikinijekkjcicg?hl=sl

**Comment by jcarrollpe** [comment]
Because you were using the known malicious RIPOFF of the original uBlock Origin by Raymond Hill aka gorhill.  That is the one you should be using from right here on Github or in the Chrome Webstore:   https://tinyurl.com/ycewo9pf

**Comment by severing77** [comment]
uBlock Origin doesn't work in Chromium browsers, this Plus version was recommended by the Paywall extension creator.

**Comment by magnolia1234** [comment]
Time to switch to Firefox on Android.

**Comment by magnolia1234** [comment]
PS I synched the supported sites between the BP Clean Chrome extension and Firefox add-on.

**Comment by jcarrollpe** [comment]
For Android this is correct, however  I've been using uBO  on both Chrome and Brave (chromium) browsers on my PC, as well as on my Chromebook...  I also use  uBO on FF (Both PC and Chromebook) along with this extension BPC. All are working fine.  As Magnolia suggested (for Android) time to move to FF but be sure and check out the uBO extension. It is also rumored Brave for Android (chromium) may support extensions soon. Best of luck!

**Comment by magnolia1234** [comment]
Well, a new Firefox v69 is rumoured not to support extensions anymore (just a built-in adblocker and 
 cookie-tracking protection) ...

**Comment by jcarrollpe** [comment]
Hate to hear that.  Firefox Beta Android v.68.5b5 is not like that yet. Your BPC and uBO working well there atm 🥇   Cheers!

**Comment by iscreamcoke** [comment]
> uBlock Origin doesn't work in Chromium browsers, this Plus version was recommended by the Paywall extension creator.

Can't you have a system-wide content blocker on Android? You just have to add the adblock-lists.

**Comment by severing77** [comment]
> > uBlock Origin doesn't work in Chromium browsers, this Plus version was recommended by the Paywall extension creator.
> 
> Can't you have a system-wide content blocker on Android? You just have to add the adblock-lists. (I'm an iOS user but I'm pretty sure it is possible)

I will try with AdGuard and Blokada to see will it work. Thanks

**Comment by severing77** [comment]
11

> PS I synched the supported sites between the BP Clean Chrome extension and Firefox add-on.

Thank you. The .xpi file for Firefox installation is not updated, still 1.6.4.0. Can I install and add the extension on my android Firefox in some other way than using that file? Like using manifest.json?

**Comment by severing77** [comment]
> 11
> 
> > PS I synched the supported sites between the BP Clean Chrome extension and Firefox add-on.
> 
> Thank you. The .xpi file for Firefox installation is not updated, still 1.6.4.0. Can I install and add the extension on my android Firefox in some other way than using that file? Like using manifest.json?

I am sorry, it was my mistake. I found the updated file. It's fine now.

**Comment by magnolia1234** [comment]
Yes, in the readme stiil previous version.
But xpi will update automatically.

**Comment by severing77** [comment]
> But xpi will update automatically.

I tried only with 1.6.4.0., but it didnt work, it didn't update automatically. I tested it on the WSJ blogs.



> Can't you have a system-wide content blocker on Android? You just have to add the adblock-lists. (I'm an iOS user but I'm pretty sure it is possible)

Here is an update regarding this. I installed the extension in Yandex browser on my android and supported it with AdGuard Premium and it manifest full performance so far, for those sites which I read mostly. I enabled Easylist and Fanboy filter lists through AdGuard. For sites I visit, only issue I noticed with frequently opening articles on Bloomberg which lately offers the robot test check. And you can not do the required check since a frame in which you do the check will not pop up.

p.s. Offtopic. Does anyone know which browser is better between Yandex and Firefox regarding the battery drain? (I assume that combination of Yandex+Adguard is harder on that, but still just comparing those two.)

**Comment by severing77** [comment]
Here is one more update too. The extension works well with on the Kiwi browser on android in combination with AdGuard Premium app, with enabled filter lists as mentioned above. Now, this combination doesn't work 100%, for instance, it doesn't work on the Economist site even it does when loaded by the Yandex browser. 

One more thing, article titles on WSJ blogs are not shown both in Chromium browsers on android and in Chrome on PC. It works well in Firefox though. This issue makes unavailable to open those articles at all.

**Comment by magnolia1234** [comment]
BP not fully working with Kiwi browser (cookie-blocking part).

WSJ blogs work fine for me now though (did you update to the latest version?).

**Comment by severing77** [comment]
> WSJ blogs work fine for me now though (did you update to the latest version?).

I updated it to 1.6.2.1 and it shows like this:

imgur.com/a/wwFLlt8

I need to disable U Block Origin so that I can see the article titles.

**Comment by magnolia1234** [comment]
I see, but that's a uBlock Origin issue and not related to BP.

**Comment by jcarrollpe** [comment]
@severing77  - For Android browsers, it's not a uBO issue.  BPC and uBO work fine together on WSJ and all their blog titles and pages show correctly on FF.  uBO also works well on Kiwi.  BPC (like BP) has never worked on Kiwi and this is a _browser_ issue the dev is apparently not interested in fixing? Brave may support extensions in Android soon. Their dev version for PC has moved Extensions out into the main menu. uBO is a great blocker with lot of community support, but it does have a learning curve.  I especially like that I can export filter rules from the PC browser I use the most (Brave), perfecting the rules and then export them to a small .txt file I keep on the cloud. I then import these rules on all my other devices. It is agnostic between browsers and works whether you are on PC/Mobile/ChromeOS.  uBO tutorial: https://www.maketecheasier.com/ultimate-ublock-origin-superusers-guide/

**Comment by severing77** [comment]
> @severing77 - For Android browsers, it's not a uBO issue. BPC and uBO work fine together on WSJ and all their blog titles and pages show correctly on FF. uBO also works well on Kiwi. BPC (like BP) has never worked on Kiwi and this is a _browser_ issue the dev is apparently not interested in fixing? Brave may support extensions in Android soon. Their dev version for PC has moved Extensions out into the main menu. uBO is a great blocker with lot of community support, but it does have a learning curve. I especially like that I can export filter rules from the PC browser I use the most (Brave), perfecting the rules and then export them to a small .txt file I keep on the cloud. I then import these rules on all my other devices. It is agnostic between browsers and works whether you are on PC/Mobile/ChromeOS. uBO tutorial: https://www.maketecheasier.com/ultimate-ublock-origin-superusers-guide/

Thank you for your comment.

I think that there is some issue with uBO in my case. Maybe I have too many filters on, which I added beside default ones. All those lists I set up in AdGuard app on my android, and now it has almost all lists used in uBO on my PC including uBO default lists which I connected through the links to uBO assets files. I quit on Kiwi regarding the extension. I use a combination of Yandex + AdGuard Premium. The issue with WSJ article titles stays. I need to find which element is blocked with uBO to disable it. I believe this will resolve that issue with no article titles loaded.

@magnolia1234 One more question, please. Since I don't have coding knowledge. I am keeping all  extension files fixed in my device storage. In Chrome, I set up all the package and .crx file for future updates on extension. My question is, for every new future update do I need to download every time new files from your site and replace them with old ones on my storage (which I am doing now). Or this .crx file is updating  the extension when new changes are published on your site on Github?

**Comment by jcarrollpe** [comment]
@severing77 <https://github.com/severing77>

>  I need to find which element is blocked with uBO to disable it. I believe
> this will resolve that issue with no article titles loaded.
>
Right on. In settings enable advanced user and you can fine tune. In
general, focus less on subscribed "filter lists" and more on *your* "my
fliters" tab.  You clearly are experienced enough to start over with less
subscribed lists and develop your own customized filter. With practice you
can take out just the right amount of ads without breaking pages. Then,
export that filter to your other devices. At least that is what works best
for me.   Don't know how Magnolia feels about all this OT discussion but
it's all in the spirit of making BPC a better experience (and separate
legitimate BPC issues from ad blockers). Cheers.

**Comment by magnolia1234** [comment]
Crx- and xpi-installations update automatically (Firefox has default update-interval of 24 hours, but will also update if you click on addon in settings).
But not possible with installation from unpacked folder (parts could be updated by loading from GitHub repo, but not all).

WSJ blogs blocking is caused by Adguard or uBlock Plus filter-list (check on desktop).
PS discussions are fine, but again just saying this issue is not caused by BP.
