### ISSUE TITLE
Site request: L'Espresso

### ISSUE THREAD

**Issue by ciru86** [magnolia1234/bypass-paywalls-chrome-clean#25]
Hi, do you think it is possibile to add L'Espresso, La Repubblica weekly magazine, to the list?
I noticed that the URL of the articles are (http://espresso.repubblica.it/plus/articoli/2020/01/31/news/la-nostra-rivoluzione-sardine-joshua-wong-1.343714?preview=true). If you change the last part in **?preview=false** the full article appears for a moment before being redirected to the preview=true version.
Don't know if that's useful in any way!
Thank you in advance!

**Comment by ciru86** [comment]
Disabling Javascript on Firefox also works!

**Comment by magnolia1234** [comment]
Fixed in latest master (preview-parameter won't be set anymore).
Also working on the provided weblink (if preview-parameter is removed).

**Comment by magnolia1234** [comment]
PS you can also use uBlock Origin with EasyPrivacy-list enabled.

**Comment by ciru86** [comment]
Thank you very much magnolia1234! I'm really glad that you guys are updating this app so often, thank you for your efforts!!
