### ISSUE TITLE
South African Newspapers

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-chrome-clean#27]
Can you please support South African Newspapers? 
Say the National ones to start with then Gauteng, Western Cape, Kwazulu Natal and the rest etc....
https://en.wikipedia.org/wiki/List_of_newspapers_in_South_Africa

**Comment by magnolia1234** [comment]
Could you be a bit more specific (and test some sites by yourself with the readme-instructions)?
Wikipedia contains an 'endless' list of newspapers.

**Comment by danielgruber8** [comment]
This explains the Paywalls in SA
https://mediaupdate.co.za/media/143199/paywalls-101-what-you-need-to-know

Not having much luck in incognito mode .... maybe it's not possible. 

https://www.businesslive.co.za/bd/companies/mining/2020-02-12-end-of-an-era-as-anglogold-exits-sa/

https://select.timeslive.co.za/news/2020-02-13-mind-the-gaps-the-real-message-of-sona-will-be-in-what-cyril-doesnt-say/

**Comment by magnolia1234** [comment]
The times/businesslive sites have premium articles with a hard paywall though.
For other sites just add a weblink with articles with an active paywall.

**Comment by danielgruber8** [comment]
https://select.timeslive.co.za/news/2020-02-13-tracking-table-mountain-killer-step-by-step/

Yes, you are right about the hard paywall but if you look in the left hand side, they also have an article limit for free articles
13 February 2020
Reading Time: 5 Minutes
Article Number: 4 / 23

**Comment by magnolia1234** [comment]
That's actually an articles-per-day counter (check another day's total).

**Comment by magnolia1234** [comment]
PS Media24 newspapers seem to have a hard paywall.
Do INMSA newspapers even have a paywall though?
