### ISSUE TITLE
Australian Newspapers

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-chrome-clean#28]
You already support a whole heap but would be good to expand it... I think some of them you can just add the domains as most papers are either Fairfax or News Corp so would most likely use the identical paywall system
https://en.wikipedia.org/wiki/List_of_newspapers_in_Australia

Thanks for your help with updating this project :)

**Comment by magnolia1234** [comment]
Could you be a bit more specific (and test some sites by yourself with the readme-instructions)?
Wikipedia contains an 'endless' list of newspapers.

**Comment by danielgruber8** [comment]
News Corp uses the same paywalls throughout I believe
https://en.wikipedia.org/wiki/News_Corp_Australia#Newspapers

I think you have most of them already anyway :)

**Comment by magnolia1234** [comment]
If you still find a missing newspaper just add a weblink of an article with an active paywall.

**Comment by danielgruber8** [comment]
WA Today has limit of 5 articles
https://www.watoday.com.au/national/western-australia/perth-school-boys-charged-after-serious-train-station-assault-leaves-man-in-critical-condition-20200214-p540s3.html

The West appears to be a hard paywall
https://thewest.com.au/news/wa/extraordinary-absolutely-brazen-and-over-in-seconds-pta-official-details-brutal-stirling-train-station-bashing-allegedly-carried-out-by-churchlands-senior-high-school-students-ng-b881462995z

**Comment by magnolia1234** [comment]
Correct, I'll add WA Today.

**Comment by magnolia1234** [comment]
WAtoday added in custom sites (no new release needed).
Just enable site in options.

**Comment by danielgruber8** [comment]
Thanks for fixing WAToday. Your response times are amazing. These appears to also be a hard paywall, but is owned by News Corp the same as the Herald Sun, The Australian which is already bypassed, I am wondering if it may still be possible to unblock it? It simply redirects to the subscribe page.
https://www.northernstar.com.au/news/coffee-plantation-sells-for-16m/3944703/ 
https://www.sunshinecoastdaily.com.au/news/dams-still-need-a-good-drink/3944999/
https://www.dailyexaminer.com.au/news/released-killer-needs-to-be-watched-carefully/3945029/

**Comment by magnolia1234** [comment]
Googlebot or disabling Javascript is not working for these sites though.

**Comment by danielgruber8** [comment]
Can you try this one? Seems similar to The Courier when only half the text shows

https://www.greatlakesadvocate.com.au/story/6622864/woes-of-celebrity-chef-george-calombaris/

**Comment by magnolia1234** [comment]
Same paywall indeed (can be fixed).

**Comment by danielgruber8** [comment]
Glad to hear :) Can you actually block the entire paywall itself, or do you have to do each domain it uses separately?

**Comment by magnolia1234** [comment]
A combination of Piano paywall-script and css-manipulation (per domain).
How many regional Advocate-sites are there (Great Lakes' paper edition has a circulation of 5000)?

**Comment by danielgruber8** [comment]
It appears that these sites are owned by ACM
https://en.wikipedia.org/wiki/Australian_Community_Media

I have listed the daily ones as those would have more recent news:

https://www.dailyliberal.com.au/story/6632528/hundreds-show-up-to-meet-dr-karl-and-celebrate-30-years/?cs=126
https://www.illawarramercury.com.au/story/6632996/serial-drink-driver-busted-outside-mt-warrigal-public-during-school-pick-up/?cs=12
https://www.dailyadvertiser.com.au/story/6631658/on-the-brink-of-mass-exodus-fire-ravaged-communities-fear-population-losses/?cs=9402
https://www.northerndailyleader.com.au/story/6632463/former-cop-jailed-for-integral-role-in-black-market-gun-sale/?cs=12
https://www.bendigoadvertiser.com.au/story/6632910/eight-bendigo-students-to-showcase-work-in-vce-season-of-excellence/?cs=10219
https://www.bordermail.com.au/story/6632650/border-couples-near-miss-after-rock-fall/?cs=9681
https://www.standard.net.au/story/6613739/still-growing-strong-after-39-years/?cs=136

**Comment by magnolia1234** [comment]
Besides The Standard they all have the same paywall as GreatLakes Advocate.

**Comment by magnolia1234** [comment]
I've just added the Australian Community Media's daily newspapers (including The Standard).

**Comment by danielgruber8** [comment]
no big deal but should watoday be merged in to the main release instead of a "custom" site?

**Comment by magnolia1234** [comment]
Adding sites inbetween-releases is a feature, not a bug ;-)
Mostly they get in the main list with a new release though.

**Comment by danielgruber8** [comment]
Can you try to add Sunshine Coast Daily if possible? 
It seems to use the same paywall as The Courier Mail.
https://www.sunshinecoastdaily.com.au/news/state-league-stalwart-rejuvenated-and-set-to-fire-/3953287/

**Comment by danielgruber8** [comment]
Can you please add Fraser Coast Chronicle?
https://www.frasercoastchronicle.com.au/news/sugar-prices-and-rain-lead-to-growing-sense-of-opt/3953090/

**Comment by danielgruber8** [comment]
Can you please add Noosa News?
https://www.noosanews.com.au/news/when-disaster-falls-who-you-going-to-call/3953640/

**Comment by magnolia1234** [comment]
Not the same as Courier Mial though, all three sites have a hard paywall for premium-articles.

**Comment by danielgruber8** [comment]
the subscribe page mentions courier mail...hmmm...

**Comment by magnolia1234** [comment]
Sure, but Googlebot loophole is not working (it's up to the newspaper if they leave that bypass open).

**Comment by danielgruber8** [comment]
Any luck with
https://www.sunraysiadaily.com.au/arts-entertainment/1058767/artist-sees-light-and-shade-in-the-mirror
Apparently they have a "basic" registration
https://www.sunraysiadaily.com.au/paywall

**Comment by magnolia1234** [comment]
Subscription-only.
Btw you're the BPC-spokesman representing all of Australia? ;-)

**Comment by danielgruber8** [comment]
The 2nd article is a "basic" article that requires free registration... surely there is a way around that.

And yeah lol :P

**Comment by magnolia1234** [comment]
> The 2nd article is a "basic" article that requires free registration... surely there is a way around that.

Yes, register for basic ;-)

**Comment by danielgruber8** [comment]
Please add https://www.maitlandmercury.com.au/story/2982988/afl-tribunal-finds-essendon-players-not-guilty-on-drug-charges/

**Comment by magnolia1234** [comment]
Another regional newspaper?
I prefer some general solution for these papers instead of adding every newspaper by domain.
PS you run some request board for these Australian sites (or do you read them all yourself)?

**Comment by danielgruber8** [comment]
Yes a general solution would be good as they seem to use the same paywall throughout their sites... maybe you can do something with a 'custom' sites? You're the paywall wizard .... 
No request board lol, just me reading. 
There is a shortage of toilet paper over here these days due to the coronavirus panics... plenty of news to read ... (and memes)

**Comment by magnolia1234** [comment]
> Yes a general solution would be good as they seem to use the same paywall throughout their sites... maybe you can do something with a 'custom' sites? You're the paywall wizard ....

Adding a custom site is the way to go plus some general rule for these Australian sites in contentScript.js (now per list of domains).
I was actually thinking about an even more general rule (for all sites), but I think your suggestion is more appropiate.

**Comment by magnolia1234** [comment]
Fix for Australian Community Media newspapers will be added in new release.
Then you can add (to custom sites) all the local newspapers you like ;-)

**Comment by danielgruber8** [comment]
Which options do I select in Custom sites to unblock Australian Community Media newspapers? 
Do I select Googlebot or Javascript or both?

**Comment by magnolia1234** [comment]
No extra options are needed.
Btw you need the latest master-zip, but I'll also add a new release today).
