### ISSUE TITLE
Could you add The New York Review of Books?

### ISSUE THREAD

**Issue by hubery98** [magnolia1234/bypass-paywalls-chrome-clean#29]
Thank you!

**Comment by magnolia1234** [comment]
Already added to extension (check options).

**Comment by hubery98** [comment]
sorry, I can't see this option. What's the name?

**Comment by magnolia1234** [comment]
Sorry, hard paywall (mix-up) ...

**Comment by hubery98** [comment]
Sorry, what do you mean? I don't understand.

**Comment by magnolia1234** [comment]
NYbooks magazine has subscription-only articles.
Very interesting site indeed though.
PS I wondered already why Adam hadn't copied my 'fix' ;-)

**Comment by hubery98** [comment]
Haha, yes. This magazine is very good, i think it's better than LRB and TLS. In a word, thank you for your development program. Moreover, I'm curious about what do you mean “ps”.

**Comment by magnolia1234** [comment]
Before I commited to Adam's repo, but he was too slow in adding new features and sites.
Now he's still copying all my fixes though ;-)

**Comment by hubery98** [comment]
I don't know this, it's embarrassed. Thank you, you are a good guy. Glad to meet you.

**Comment by magnolia1234** [comment]
You're welcome. Spread the word.
