### ISSUE TITLE
[New Site Suggestion] Caller Times/USA Today Network

### ISSUE THREAD

**Issue by rourpab** [magnolia1234/bypass-paywalls-chrome-clean#30]
Gannett owns USA Today & a slew of other newspapers listed here: https://www.gannett.com/brands/

They feature Subscriber Only content such as this article by the Caller Times: https://www.caller.com/story/news/2020/02/17/figg-stands-safety-record-corpus-christi-caller-times-ad/4785556002/

Or this one by the Record Searchlight: https://www.redding.com/story/news/2020/02/15/2020-election-shasta-county-measure-a-measure-b-tax/4671076002/

**Comment by magnolia1234** [comment]
Yes, these can be fixed by setting Googlebot in BPC-extension.
You can also use ModHeader though.

**Comment by danielgruber8** [comment]
Where is this Googlebot setting? I just see the list of the various sites to tick and untick

**Comment by magnolia1234** [comment]
> Where is this Googlebot setting? I just see the list of the various sites to tick and untick

There is no UI to add your own Googlebot setting for a site.
I've been thinking about such a new feature though.
Might be usefull for the regional 100+ USA Today sites.

**Comment by magnolia1234** [comment]
With new BPC v1.6.4.1, you can add your own custom sites.
Caller Times and Redding need Googlebot bypass enabled.
