### ISSUE TITLE
contact info

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-chrome-clean#32]
are you able to add your e-mail info on the readme 
in case you need to be contacted privately or for tech support
github has disabled private messages

**Comment by magnolia1234** [comment]
Obviously not, just by adding an issue or comment.

**Comment by danielgruber8** [comment]
Maybe I want to hire u or ask u something unrelated? :)
can set a protonmail address etc

**Comment by magnolia1234** [comment]
Sorry, I'm no gigolo ;-)

**Comment by magnolia1234** [comment]
PS I see you follow me now, but you also watch a specific repo with the above mentioned notification options.
