### ISSUE TITLE
Notification of updates?

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-chrome-clean#33]
Is there a way to get a notification that there is a new update available besides keep looking on Github every day ;) ?

**Comment by magnolia1234** [comment]
In desktop-view you can click on the watch-button of a repo and select the notifications you want (releases only or watching all/only your issues etc.).

**Comment by danielgruber8** [comment]
I just did that thx
But still would be nice to get an app notification

**Comment by magnolia1234** [comment]
That's the major downside of an extension outside of the Chrome Webstore.
But I've been thinking about an update notification in the options page though.

**Comment by magnolia1234** [comment]
Show available new release in popup (click icon):
https://github.com/magnolia1234/bypass-paywalls-chrome-clean/commit/4f613e0bba0ef3ecb1819187e69245a4e2ed398e

**Comment by danielgruber8** [comment]
There is a small bug in the code :) 

The new version has this error in chrome://extensions

Uncaught (in promise) TypeError: Cannot set property 'innerText' of null
Context
options.html
Stack Trace
version.js:16 (anonymous function)
				document.getElementById('version_new').innerText = versionString_new;

**Comment by magnolia1234** [comment]
Fixed (also version-check in options.html now).

**Comment by danielgruber8** [comment]
Can you also add the version number in the respective Readme file? (both Chrome and Firefox releases)

**Comment by magnolia1234** [comment]
Sure (already on releases page), but make up your mind ;-)
You don't want to check the site all the time, but now you want the version-number also on the readme page.

**Comment by danielgruber8** [comment]
It's entirely your choice as top dog of the app.... but I think it's handy to have it also on readme page as that is the front/main page of Github, i.e. the very first page you see. NEW users to the app would not have it installed yet to receive the pop up :)
