### ISSUE TITLE
Can't sign into medium.com at all.

### ISSUE THREAD

**Issue by johnsaucier** [magnolia1234/bypass-paywalls-chrome-clean#35]
Is there a way to add exceptions, or turn it off per site?

The only way I can login to my medium account is to turn it off entirely. If I login, and then try turning it back on, medium acts as if I'm not logged in again. I'd love to be able to turn it off per site.

**Comment by magnolia1234** [comment]
In the options you can disable the bypass for Medium (or any other site).
