### ISSUE TITLE
Not working on latest version of Brave MacOS

### ISSUE THREAD

**Issue by TI-0** [magnolia1234/bypass-paywalls-chrome-clean#36]
The extension loads but the enable/disable toggle is greyed out & can't be selected. I tried both installation instructions. Is there any way to bypass this ? Thanks.

**Comment by magnolia1234** [comment]
Seems like a Brave issue with extensions not in Chrome's Webstore.
Maybe switch to Vivaldi browser?

**Comment by magnolia1234** [comment]
PS in Brave on Windows I can still install the BPC extension (load unpacked in developer mode). Unpack master zip-file.

**Comment by jcarrollpe** [comment]
Try the dev version of Brave. I had to move up channels for this reason. I now run dev on Windows 10 (x64) and Linux (debian) on my Chromebook. BPC works like a champ with zero problems. Dev versions of Brave have moved the Extensions out of "More tools" into the main menu- a distinct departure from Chrome and signaling their continued extension support, potentially extending to Android 10.   [https://www.brave.com/download-dev](url)
