### ISSUE TITLE
SeekingAlpha Site Won't Load

### ISSUE THREAD

**Issue by Skates1616** [magnolia1234/bypass-paywalls-chrome-clean#38]
After updating the extension and enabling SeekingAlpha support, the webpage will not load.

Refer to attached image of what actually loads.
![https   seekingalpha com  source headtabs](https://user-images.githubusercontent.com/23196661/75553382-e9109f00-59fd-11ea-86e6-0e9ba3f6c6c9.png)

**Comment by magnolia1234** [comment]
Looks like source-code of webpage.
Maybe conflict with other (user-agent)extension?
BPC is working just fine here though.

**Comment by Skates1616** [comment]
It must have been a server issue on their end, I just tried again with no changes and it works.  Sorry for the false alarm.

**Comment by Skates1616** [comment]
While I have your ear, did you have any luck with getting the script to function on iOS?

**Comment by magnolia1234** [comment]
> While I have your ear, did you have any luck with getting the script to function on iOS?

No plans, but you could use some Shortcuts scripts.

**Comment by danielgruber8** [comment]
I also had seen the source code on the Seeking Alpha site.... but working now. :)

**Comment by danielgruber8** [comment]
What are Shortcuts scripts?

PS: Are you magnoliaflower1213 on instagram? Don't wanna follow the wrong guy....

**Comment by magnolia1234** [comment]
> What are Shortcuts scripts?
> 
> PS: Are you magnoliaflower1213 on instagram? Don't wanna follow the wrong guy....

On Reddit you can find scripts to bypass paywalls for the iOS Shortcuts app.
PS no social media for me.
