### ISSUE TITLE
BPC is being silently stripped out of (Windows x64) M81 Chrome browser

### ISSUE THREAD

**Issue by jcarrollpe** [magnolia1234/bypass-paywalls-chrome-clean#39]
On my Windows PC's I run BPC on both Chrome Beta and Brave Dev chromium browsers side by side. They share a common dedicated folder for BPC master zip dumps. Recently Chrome beta updated to M81 and I noticed the BPC extension was missing. Brave Dev is working, but still based on M80.  I used "load unpacked" to reinstall the extension in Chrome. Upon restarting the extension was gone again. No pop-up, no nag or notification- nothing. I reloaded again and restarted. Gone again. At first I thought it may have been introduced with v1.6.4.1 but have now confirmed the same behavior with v1.6.3.1.  Brave Dev continues to work and retains either version after multiple re-starts but it is still based on M80. Chrome M81 is stripping out BPC (maybe any non-Store extension) without any warning or notifications. 
Chrome Version 81.0.4044.34 (Official Build) beta (64-bit)
Brave Version 1.6.53 Chromium: 80.0.3987.122 (Official Build) dev (64-bit)

I really hope there is a workaround found for this. Who knows, maybe there is a new flag that controls this behavior. I will look and ask around. At every step Chrome is slowly squeezing out non-Store extensions on the desktop, and refuses support any extensions in Android. Meanwhile Brave continues to support almost all extensions and is working on adding extension support to their (chromium) Android browser. I'm very impressed with Brave and they also support Linux and IOS.

**Comment by magnolia1234** [comment]
BPC is working just fine for me in portable version of Chrome 81 beta (same version as yours) though (load unpacked in developer mode).
