### ISSUE TITLE
[Bug] Local storage cleared erroneously

### ISSUE THREAD

**Issue by narcolepticinsomniac** [magnolia1234/bypass-paywalls-chrome-clean#4]
Cent 4.1.7.182 (Official Build) (64-bit) (portable) (Chromium 78.0.3904.108)

Switched to this fork today, and while it has some improvements, I very quickly started noticing prefs vanishing into thin air. 1.6.1.3 is constantly clearing local storage on every site.

**Comment by magnolia1234** [comment]
So did the old version though (on all enabled domains).
Default behavior to prevent respawning cookies.

**Comment by narcolepticinsomniac** [comment]
Nah, man. By "every site", I meant literally everywhere. Every single completely unrelated site you visit.

**Comment by magnolia1234** [comment]
I'll look into it. Do you have an example site?
Probably caused by (new) blocking option of general paywall-scripts (try to disable these in options). I'll add them to the hold_localstorage list.

**Comment by narcolepticinsomniac** [comment]
You can test anywhere. Open the console on this page and run `localStorage.setItem('test', 'true')`. Switch to the application tab, find the entry in local storage, then reload the page. Poof... gone.

![local storage](https://user-images.githubusercontent.com/14100003/72320768-5778e800-3670-11ea-9436-bd22e36271be.png)

**Comment by magnolia1234** [comment]
Not caused by BP (neither for blocked general paywall-scripts).
Tested on Chrome 79/Win10.

**Comment by narcolepticinsomniac** [comment]
IDK man, I'm pretty sure. Only started happening after I installed the latest crx, and I can repro like clockwork. Here's a [screen record](https://streamable.com/ngfr7) of a test without it enabled, and then with it enabled.

**Comment by magnolia1234** [comment]
Looks like some kind of extension conflict (what's content.js?).
I can't reproduce it with the latest crx-file or master-zip though.

**Comment by narcolepticinsomniac** [comment]
IDK what to tell you. I'm certainly confused by the fact that we're not seeing the same thing. It's not a conflict though. I can repro 100% of the time in a brand new vanilla Chromium dev. Even just enabling it and switching to the tab deletes the key. [Screen record](https://streamable.com/6eft2)

**Comment by magnolia1234** [comment]
Strange indeed. I also tested it with 'your' Cent Browser (+ Portable): no issues for me ...

**Comment by iscreamcoke** [comment]
This is a known issue.

I can reproduce the exact same problem, unless I save BP's options during the installation when the pop-up is prompted.* Can you try that and tell us if it changes anything @narcolepticinsomniac

_* saving options anytime after installation should work too_

**Comment by magnolia1234** [comment]
A save-instruction should do then ;-)
I wonder what weird happens if you don't save (no sites enabled, I would figure).

**Comment by iscreamcoke** [comment]
If you don't save, i'll clear local storage for all sites.

I told you so, it instantly log me out from github, google, twitter, etc.

I don't think this issue was present in the old version though. While replacing all_sites with the list of supported website in manifest.json would solve the issue, it adds yet another step when introducing a new url

**Comment by iscreamcoke** [comment]
If you don't save, i'll clear local storage for all sites, so it's rather 'all sites enabled' than 'no sites enabled' (I told you so back then, it instantly logs me out from github, google, twitter, etc. but it seems it's not a mac-only thing now)

I don't think this issue was present in the old version though. While replacing all_urls with the list of supported websites in manifest.json should solve the issue, it adds yet another step when introducing a new url

**Comment by magnolia1234** [comment]
Yes, but you only told me at the end that you hadn't saved the options.
I'll test this not-saving-scenario later though.

**Comment by iscreamcoke** [comment]
It's probably a misunderstanding then. I **have** to save options for google, github not to log me out. It's just that it's not compulsory to do it during installing (I can do it anytime but I must do it)

**Comment by magnolia1234** [comment]
Yes, probably same issue. All sites enabled indeed.
Btw your issue was also only with my fork?

**Comment by iscreamcoke** [comment]
Yes, since I can say I've tested virtually all your releases, it certainly dates back to the introduction of .json lists (which is a great _per se_, we just need to resolve those bugs and the clean-extension will rock)

**Comment by narcolepticinsomniac** [comment]
> Can you try that and tell us if it changes anything @narcolepticinsomniac?

Yep, saving options eliminates the bug. All sites are enabled by default though, so I imagine most users would assume everything's good to go without needing to save. Should be a pretty simple fix though.

**Comment by magnolia1234** [comment]
Custom/block-scripts headers (with empty string value as 'domain') in json cause a problem when not saving the options ...
All DefaultSites are saved anyway, but not by the options-form (where they would be filtered).
The empty string matches with all domains you'll visit and so clearing its cookies and local storage.
I'll add an extra filter in background.js.

**Comment by magnolia1234** [comment]
Fixed in v1.6.1.4. Weird bug indeed.

**Comment by iscreamcoke** [comment]
Works well with 1.6.1.4. Thanks Magnolia

**Comment by magnolia1234** [comment]
You're welcome.
Btw someone is complaining about your removal of Liberation (3-article-limit without the right uBlock Origin filters) ;-)

**Comment by iscreamcoke** [comment]
that's weird, I'm not hitting a metered-paywall on Libération. Can you link me the issue?

**Comment by magnolia1234** [comment]
Adam's repo, search Liberation.
Blocked by uBlock and also DisConnect.

**Comment by iscreamcoke** [comment]
Added in my PR, you can close the issue

**Comment by narcolepticinsomniac** [comment]
LGTM, thanks.

**Comment by magnolia1234** [comment]
https://7esl.com/acronyms ;-)
