### ISSUE TITLE
No, thanks alternative

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-chrome-clean#40]
Do you think you can make your own repository without the €9.85 yearly subscription fee?
https://addons.mozilla.org/en-US/firefox/addon/no-thanks/

**Comment by magnolia1234** [comment]
Subscription for an experimental add-on ...?
You're not using uBlock Origin?
Review quote:
Area of concern is code transparency, particularly with the required permissions and evidently the subscription's hash check. This is not to be mistaken for a privacy policy, which is available on the WX's home page.

The WX seems to update directly from the developer's source and thereby bypassing Mozilla's screening (for what that is worth these days) and thus raises another potential code transparency flag.

**Comment by danielgruber8** [comment]
I do indeed use UBlock origin (moved from adblock plus years ago), but the extension says it blocks additional content: hides or auto-closes many kinds of annoyances usually **not** covered by ad blockers: **newsletter pop-ups, chat boxes, survey/opinion pop-ups, "Allow notifications" pop-ups and many others**

**Comment by magnolia1234** [comment]
I have never used it, but it seems like an elaborate way to earn some money with an add-on.

**Comment by danielgruber8** [comment]
Why not do your own?

**Comment by magnolia1234** [comment]
It's not open-source and it seems I'm not missing out on the supposed features though.
