### ISSUE TITLE
Adult sites

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-chrome-clean#41]
I am not sure if you are able to bypass the "free" subscription limitations of adults only mens sites 

e.g. manhunt.net (and there are others similar to this)
The free version would only allow viewing thumbnail images instead of full size, limit daily profile views or have a daily message limit etc

Can discuss privately but you don't release your e-mail

Apologies if off-topic (so feel free to close) but your script says "bypass paywalls" - not just "newspapers"....

**Comment by magnolia1234** [comment]
Off-topic indeed ;-)
