### ISSUE TITLE
new site campaignlive.co.uk

### ISSUE THREAD

**Issue by hrvojepilic** [magnolia1234/bypass-paywalls-chrome-clean#42]
Please add:
https://www.campaignlive.co.uk/ @

**Comment by magnolia1234** [comment]
You can add this site to custom sites without any further settings (will remove cookies).

**Comment by hrvojepilic** [comment]
Doesn't work when I add as custom site, but I made it working with Disable Cookies extension. thanks

**Comment by magnolia1234** [comment]
> Doesn't work when I add as custom site, but I made it working with Disable Cookies extension. thanks

You also have to enable the custom site in options though (works for me).

**Comment by hrvojepilic** [comment]
Yeah, I have checked under options page. 
I'm using this 
`{"Campaign Live":{"domain":"campaignlive.co.uk"}}`

**Comment by hrvojepilic** [comment]
I got it working after I deselected all and selected all under options despite it's being selected when I opened the options.

**Comment by magnolia1234** [comment]
Weird, worked for me the first time.
