### ISSUE TITLE
economist.com - URLs not working

### ISSUE THREAD

**Issue by hrvojepilic** [magnolia1234/bypass-paywalls-chrome-clean#44]
Hi,

hyperlinks inside the article aren't clickable when using the extension, when accessed without extension and in incognito, URLs work fine

For example - https://www.economist.com/the-world-this-week/2020/03/05/business-this-week

Do you have any idea what is happening?

Thanks

**Comment by hrvojepilic** [comment]
...also Menu when clicked is not responding.

**Comment by magnolia1234** [comment]
Yes, i've seen this behaviour before (some kind of javascript links).
The next day it was gone, but this can be fixed though.

**Comment by hrvojepilic** [comment]
I've been seeing this for some time, it was the same on iamadamdev version too.

**Comment by magnolia1234** [comment]
Not active for me at the moment.
Could you right-click an Economist link - inspect and sent me the html-code?

**Comment by magnolia1234** [comment]
Ah, indeed also active for me on the link you sent me ...

**Comment by hrvojepilic** [comment]
Can you fix the nav links too?

**Comment by florida922** [comment]
Menu is out because of blocking paywall-script.

**Comment by magnolia1234** [comment]
Menu is out because of blocking paywall-script.
