### ISSUE TITLE
Was pulling out "Latest Version" from icon intentional?

### ISSUE THREAD

**Issue by jcarrollpe** [magnolia1234/bypass-paywalls-chrome-clean#45]
Just checking. I didn't see any mention in the changelog.  It may have been inadvertent. Don't think it warrants another release. If the intention is for it to be there, just add it back in the next rev.  I watch releases so I know when a new rev is up. Thanks.

**Comment by magnolia1234** [comment]
Yes, but only mention now when there is a new release.

**Comment by jcarrollpe** [comment]
Makes sense, thanks.
