### ISSUE TITLE
Yandex browser 

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-chrome-clean#46]
I followed your instructions but can't add your script to the yandex browser in Android.
See attached error. 
![Screenshot_20200309-173809](https://user-images.githubusercontent.com/35402207/76189912-e1d46700-622f-11ea-91f4-a8971ad5b4db.png)

**Comment by magnolia1234** [comment]
Zip-file is working just fine for me though (load unpaked folder in developer mode)?
You used the crx-file, I guess?

**Comment by danielgruber8** [comment]
Yes I enabled developer mode. I expanded the zip file in to sdcard\Downloads\bypass-paywalls-chrome-clean-master and tried to load the manifest.json file inside that folder as per your instructions.

**Comment by magnolia1234** [comment]
Master zip-file contains an extra folder (look for manifest.json file).

**Comment by danielgruber8** [comment]
Yes manifest.json was what I tried to add to Yandex and came up with that error message

**Comment by florida922** [comment]
I'm not sure what goes wrong on your end, but a new install works still fine for me (Android 9).

**Comment by magnolia1234** [comment]
I'm not sure what goes wrong on your end, but a new install works still fine for me (Android 9).

**Comment by danielgruber8** [comment]
I am using Android 10. Should I use the crx file?

**Comment by danielgruber8** [comment]
So I copied the BPC folder from Downloads to Documents and now it worked.

Permissions issue in Downloads folder? It's weird....

**Comment by magnolia1234** [comment]
Maybe you didn't unpack the zip-file?

**Comment by danielgruber8** [comment]
I did

**Comment by magnolia1234** [comment]
Well, since it's working now I'll stop guessing then.
