### ISSUE TITLE
Not working on Linux Mint

### ISSUE THREAD

**Issue by shrox** [magnolia1234/bypass-paywalls-chrome-clean#48]
Getting the errors as seen in the screenshot. 
![Screenshot from 2020-03-11 21:54:21](https://user-images.githubusercontent.com/7929530/76439933-2a805180-63e3-11ea-86b5-8655a465e041.png)

**Comment by magnolia1234** [comment]
I can reproduce the first error at new install, but I'm not getting the 2nd one.
Can you check at which line in background.js this happens?

**Comment by shrox** [comment]
Does this help?
![Screenshot from 2020-03-12 00:03:03](https://user-images.githubusercontent.com/7929530/76451076-e26a2a80-63f4-11ea-9d4a-182a6868b2d9.png)

**Comment by magnolia1234** [comment]
Can you test the latest master-zip file?
https://github.com/magnolia1234/bypass-paywalls-chrome-clean/archive/master.zip

**Comment by shrox** [comment]
Yes, this works! Thanks :)

**Comment by magnolia1234** [comment]
Btw which Chrome/Chromium version are you using?

**Comment by shrox** [comment]
Oh yes, I haven't updated it for a while (data limitations). It's Version 70.0.3538.67 (Official Build) (64-bit)

**Comment by magnolia1234** [comment]
Ah, that might be an explanation for the 2nd error.

**Comment by magnolia1234** [comment]
I reverted the extraHeaders 'fix', it's needed for setting the referer in Chrome.

**Comment by shrox** [comment]
Okay. Updating Chrome should fix it though, right?

**Comment by magnolia1234** [comment]
Yes, or use the Firefox add-on (also auto-update).

**Comment by magnolia1234** [comment]
PS extraHeaders-option was introduced in Chrome 72.

**Comment by shrox** [comment]
All right. Thanks!
