### ISSUE TITLE
www.ft.com not working

### ISSUE THREAD

**Issue by vic958420** [magnolia1234/bypass-paywalls-chrome-clean#49]
Suddenly getting a paywall today:
![www ft com_content_2e703c9e-5474-4935-8740-441dc43224b4](https://user-images.githubusercontent.com/38735851/76579329-2bc48380-64a2-11ea-9653-bcdf66f40bdb.png)

**Comment by magnolia1234** [comment]
Fixed in latest master: https://github.com/magnolia1234/bypass-paywalls-chrome-clean/archive/master.zip
Or until new crx-release you can add custom site with domain ft.com (use unique title) and googlebot-fix.
