### ISSUE TITLE
Use js command for bookmarklet

### ISSUE THREAD

**Issue by adlqgn** [magnolia1234/bypass-paywalls-chrome-clean#5]
Hello,

Is there a way to use these js bypass commands for one specific website, and convert them to a bookmarklet to use in iOS Safari?

Thank you for your work!

**Comment by magnolia1234** [comment]
Probably, but I've got no experience with iOS bookmarklets or Shortcuts.

**Comment by iscreamcoke** [comment]
I'll look into it asap, this function has been requested several times

But you can already block paywall-scripts (tinypass.com, poool.fr, etc.) with iOS adblocker like 1Blocker

**Comment by iscreamcoke** [comment]
For the record, there's this iOS shortcut : https://www.icloud.com/shortcuts/71648f5ad34f4d8f972718e5f3621ffe

The method is interesting: it works by encoding the url into with base 64. I tested it successfully with several websites like WSJ, FT, NYT (it doesn't work for other like lemonde.fr).

**Comment by iscreamcoke** [comment]
For the record, there's this iOS shortcut : https://www.icloud.com/shortcuts/71648f5ad34f4d8f972718e5f3621ffe

The method is interesting: it works by encoding the url into with base 64. I tested it successfully with several websites like WSJ, FT, NYT (it doesn't work when a referrer is needed though, like lemonde.fr).

**Comment by iscreamcoke** [comment]
@magnolia1234  those are literally all the functions used by the shortcut:

![82613015_570945947088686_3831890523510013952_n](https://user-images.githubusercontent.com/17458353/72840124-e2bb3480-3c93-11ea-8214-bd558ffd1dde.jpg)
