### ISSUE TITLE
New site request Caixin

### ISSUE THREAD

**Issue by AFlyingBird90** [magnolia1234/bypass-paywalls-chrome-clean#54]
Hi, caixin.com (Chinese version of caixinglobal.com) paywall can't be bypassed in incognito mode, while caixinglobal.com paywall has been bypassed. Any chance you will be able to add caixin.com?

**Comment by magnolia1234** [comment]
For Caixin the Googlebot-fix doesn't work.
Looks like a hard paywall (subscription-only).

**Comment by AFlyingBird90** [comment]
thanks
