### ISSUE TITLE
washington post

### ISSUE THREAD

**Issue by hrvojepilic** [magnolia1234/bypass-paywalls-chrome-clean#55]
Do you have any ideas why I keep getting redirected to GDPR consent page, can't even load hompege?
P.S. I'm browsing from EU.

**Comment by magnolia1234** [comment]
Works just fine for me though.
BPC holds on to wp_gdpr cookie.
Your using another extension to block/erase WaPo cookies?

**Comment by hrvojepilic** [comment]
Thanks, it worked when I turned off I don't care about cookies.

**Comment by magnolia1234** [comment]
Fine, but it should also work with that extension though.
