### ISSUE TITLE
Site request: Australian Jewish News / Times of Israel

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-chrome-clean#58]
https://ajn.timesofisrael.com/
https://www.timesofisrael.com/

Browsing of the digital edition seems to be hard paywalled, but maybe you have some magical ideas?

Melbourne
http://edition.jewishnews.net.au/html5/reader/production/default.aspx?&edid=053429f9-edfa-4dbe-ab66-a1616503bccf

Sydney
http://edition.jewishnews.net.au/html5/reader/production/default.aspx?&edid=e9f84180-c5fa-4a49-9e1c-4eb7150a1ae3

**Comment by frantzkamus** [comment]
From what I've seen, digital versions will always be under a hard paywall, as they don't need to have they content indexed by Google contrary to the main website.

Can you provide links of articles under a paywall on timesofisrael.com or jewishnews.net.au?

**Comment by magnolia1234** [comment]
>Browsing of the digital edition seems to be hard paywalled, but maybe you have some magical ideas?

Indeed har paywall.
No paywall on regular website though.

**Comment by danielgruber8** [comment]
Thanks anyway :)
