### ISSUE TITLE
youtube

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-chrome-clean#61]
Not a paywall (well maybe youtube premium) but do you know what i add on ublock origin to get rid of this youtube advertising text which appears on top of each video title i watch? I'd like a coronavirus free youtube thanks......

Coronavirus disease (COVID-19)
Get the latest information from the Australian Government Department of Health about COVID-19.
Department of Health

**Comment by magnolia1234** [comment]
Even with a Australian VPN-connection I don't see the text though.
If it's a text overlay you can try to block the element with uBlock (right-click).

**Comment by frantzkamus** [comment]
This isn't an ad but an official message from you national health department... But as magnolia has said, you can probably manually block it with the uBlock picker

**Comment by danielgruber8** [comment]
It appeared when I did a search
https://www.youtube.com/results?search_query=bill+gates+coronavirus
I tried to right click it with ublock but had trouble to drag it

**Comment by magnolia1234** [comment]
Figures, you searching for 'coronavirus'.

You don't need to drag it, but right-click and block element.
Use the ccs-selector which hides the element completely.
Or add in 'my filters':
www.youtube.com##ytd-clarification-renderer.ytd-item-section-renderer.style-scope

**Comment by danielgruber8** [comment]
That filter removed it off the search results, but it still stubbonly appearing on top of YT videos
The + symbol comes up when I use block element and it doesn't let me highlight the whole box
https://www.youtube.com/watch?v=as9JRKed7Cs

**Comment by magnolia1234** [comment]
Do you have a screenshot?
I don't get the message on top of the Youtube video, but I probably have more uBlock filters activated.

**Comment by danielgruber8** [comment]
![Screenshot_20200323-184808](https://user-images.githubusercontent.com/35402207/77293793-246d6780-6d37-11ea-88ac-1cddd66437fa.png)

**Comment by magnolia1234** [comment]
Okay, but that's not a message 'on top' of the video though.
You can block this clarify-box in uBlock (myFilters):
www.youtube.com###clarify-box

**Comment by danielgruber8** [comment]
It's gone now. Hooray! :) 
Now I can watch my music in peace
Cheers
