### ISSUE TITLE
WSJ Not Working in Chrome V80

### ISSUE THREAD

**Issue by wigguslong** [magnolia1234/bypass-paywalls-chrome-clean#62]
Hi guys, 

WSJ is not working in Chrome V80 with this extension. 

Fix possible? 

Thanks.

**Comment by magnolia1234** [comment]
Fixed in latest master-zip.
Also check #59

**Comment by wigguslong** [comment]
Thank you, the new version worked. 
For some reason the extension does not update to the latest version, I had to reinstall but anyway, the issue is solved. Thanks.

**Comment by magnolia1234** [comment]
Indeed, in Chrome you have no auto-update functionality.
If you use a GitHub client then you can clone the repo and update (pull origin) that way though.
