### ISSUE TITLE
One-hundred stars ⭐

### ISSUE THREAD

**Issue by jimmydeuxfois** [magnolia1234/bypass-paywalls-chrome-clean#64]
Thank you for the new repo. I have provided your 100th star. Well deserved

⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐🌟<- my 100th star

**Comment by magnolia1234** [comment]
You're welcome, but long time no see.

**Comment by jimmydeuxfois** [comment]
Yes I came back to thank you for keeping the updates on during the pandemics 🥇
