### ISSUE TITLE
Request to add the site The New Republic

### ISSUE THREAD

**Issue by inigma1** [magnolia1234/bypass-paywalls-chrome-clean#66]
Could you please add the site The New Republic (www.newrepublic.com)?

The link to the article is as follows:
https://newrepublic.com/article/157007/left-bigger-bernie-sanders

Thank you.

**Comment by magnolia1234** [comment]
Interesting addition for BPC.
Just added in latest master-zip.
Btw also blocked by uBlock Origin with filter EasyPrivacy.
