### ISSUE TITLE
The ZIP file is several versions behind the CRX. The Times does not work in the ZIP version.

### ISSUE THREAD

**Issue by avengah** [magnolia1234/bypass-paywalls-chrome-clean#71]
Since the CRX does not work in Chrome, I am unable to update to the latest version to see if the issue with The Times has been fixed. Thanks!

**Comment by avengah** [comment]
Never mind, I screwed up file paths

**Comment by avengah** [comment]
The Times still doesn't work.

https://www.thetimes.co.uk/article/coronavirus-bailout-will-compensate-2m-self-employed-workers-6228m36nr

**Comment by magnolia1234** [comment]
Since it works still fine there's no fix needed though.
Maybe check the user-agent (Googlebot) and referer (Google) in the RequestHeaders (of a html-document):
https://mkyong.com/computer-tips/how-to-view-http-headers-in-google-chrome

**Comment by avengah** [comment]
It's working fine now, no idea why it wasn't before. Thanks!
