### ISSUE TITLE
tagesanzeiger.ch & nzz.ch

### ISSUE THREAD

**Issue by bendschs** [magnolia1234/bypass-paywalls-chrome-clean#72]
please add tagesanzeiger.ch, swiss newspaper

**Comment by magnolia1234** [comment]
Premium articles have a hard paywall (subscription-only).

**Comment by bendschs** [comment]
ok, thank you. however it works for nzz.ch, which seems to have a subscription-wall as well

**Comment by magnolia1234** [comment]
Not all paywalls are the same though.
Nzz.ch needs a simple cookie-fix indeed.
You added it to your custom sites?

**Comment by bendschs** [comment]
exactly!

**Comment by magnolia1234** [comment]
I'll add nzz.ch later then to BPC.

**Comment by bendschs** [comment]
thanx a lot for the great work!

**Comment by magnolia1234** [comment]
Neue Zürcher Zeiting added to BPC.
