### ISSUE TITLE
The Atlantic banners

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-chrome-clean#73]
I removed the coronavirus subscription nags using UBlock Origin, but I had to add 3 filters before it worked. I'm so n00b at this. Not sure if there is a better way? Also whether it should be incorporated in to BPC or not.

www.theatlantic.com##p.c-non-metered-nudge__text--main.c-non-metered-nudge__text:nth-of-type(1)
www.theatlantic.com##.c-non-metered-nudge__container-container
www.theatlantic.com##.c-non-metered-nudge--article.c-non-metered-nudge--non-homepage.is-visible.js-non-metered-nudge.c-non-metered-nudge

**Comment by magnolia1234** [comment]
This works also:
www.theatlantic.com##.c-non-metered-nudge

**Comment by danielgruber8** [comment]
Hi mate, 
I added www.theatlantic.com##.c-non-metered-nudge  but it's still showing the article limit nudge

**Comment by magnolia1234** [comment]
For articles also add:
www.theatlantic.com##.c-nudge__container
PS uBlock Origin issues/forum are closed? ;-)

**Comment by danielgruber8** [comment]
Lol, they also closed the Aussie borders now :) 
How unfortunate you can't visit us
Anyway you might want to integrate with BPC
