### ISSUE TITLE
washington post / american affairs journal banners

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-chrome-clean#74]
Should these UBlock Origin filters be incorporated with BPC
www.washingtonpost.com##.promo.signup.subscription.content-subscription
americanaffairsjournal.org##.paywall-notification-bar-wrapper

**Comment by danielgruber8** [comment]
Also I removed filters from australianfrequentflyer.com.au as i was unable to browse their forum without popups/nags appearing
www.australianfrequentflyer.com.au##.HDzjDoKPgdfH-default
www.australianfrequentflyer.com.au##.HDzjDoKPgdfH-bg

Anyway to combine these 2 filters in to 1?

**Comment by magnolia1234** [comment]
> hould these UBlock Origin filters be incorporated with BPC
> [www.washingtonpost.com##.promo.signup.subscription.content-subscription](http://www.washingtonpost.com##.promo.signup.subscription.content-subscription)
> americanaffairsjournal.org##.paywall-notification-bar-wrapper

AmericanAffairs-banner already in BPC.
WaPo-banner could be added.

**Comment by magnolia1234** [comment]
This should work:
www.australianfrequentflyer.com.au##[class^="HDzjDoKPgdfH"]

**Comment by danielgruber8** [comment]
Did you add WaPo banners to BPC ?

**Comment by magnolia1234** [comment]
> Did you add WaPo banners to BPC ?

No, didn't see them.
Also uBlock is more flexible in blocking banners.
