### ISSUE TITLE
site request: brisbane times

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-chrome-clean#75]
Can you please remove the 5 article limit for www.brisbanetimes.com.au
Same publisher as theage.com.au
Not sure if it's a Googlebot or cookie fix or both?

Cheers

**Comment by magnolia1234** [comment]
Have you tried adding a custom site?

**Comment by danielgruber8** [comment]
No as I did not know whether to use Googlebot / Javascript etc

**Comment by danielgruber8** [comment]
Also Brisbane is a major capital city, not a regional paper :)

**Comment by magnolia1234** [comment]
If it's just a 5-article-limit then Googlebot or Javascript-block are not needed.
Just add it as custom site first.

**Comment by danielgruber8** [comment]
Seems to work :+1: ... maybe the instructions can clarify so n00bs know when to use Googlebot / Javascript block 

Also what filter can I add to UBlock Origin to stop the videos from auto-playing? It's very annoying
https://www.brisbanetimes.com.au/business/companies/myer-closes-all-stores-in-response-to-coronavirus-20200327-p54eqs.html

**Comment by danielgruber8** [comment]
Ditto with videos auto-playing here too
https://www.heraldsun.com.au/entertainment/celebrity/prince-charles-diagnosed-with-coronavirus/news-story/8602788066cfd42b766ff31f90c3856e

**Comment by magnolia1234** [comment]
A metered paywall just requires a cookie-fix.
Btw Google is also disabled on your device? ;-)
https://www.groovypost.com/howto/disable-autoplay-videos-on-sites-in-google-chrome

**Comment by danielgruber8** [comment]
that google chrome option no longer exists since 2018 lols... :p

**Comment by magnolia1234** [comment]
Next sentence: 3rd-party extensions ...
