### ISSUE TITLE
New Site Request: www.livemint.com

### ISSUE THREAD

**Issue by inigma1** [magnolia1234/bypass-paywalls-chrome-clean#76]
Could you please add www.livemint.com?

Article I was accessing got blocked after reaching the limit for free articles:
https://www.livemint.com/news/world/italy-coronavirus-deaths-rise-by-919-highest-daily-tally-since-epidemic-began-11585327464135.html

Thank you

**Comment by magnolia1234** [comment]
Metered paywall can be fixed by adding custom site (no further options needed).

**Comment by magnolia1234** [comment]
PS not a metered paywall, but an external Javscript-file has to be blocked (not working with custom sites).
I'll add the site later.

**Comment by inigma1** [comment]
Cool, thanks

**Comment by magnolia1234** [comment]
Just added.
