### ISSUE TITLE
Telegraaf.nl premium page keeps refreshing

### ISSUE THREAD

**Issue by mistere31** [magnolia1234/bypass-paywalls-chrome-clean#77]
Since 2 days the premium pages of telegraaf.nl keeps refreshing when bypass paywalls is active. Source code of the site still shows the full article content. Disabled U-Block as well, still same problem. Appears in Chrome, Vivaldi and Firefox. All plugins updated.

**Comment by magnolia1234** [comment]
Where do you still see the full article content though (html element)?

**Comment by mistere31** [comment]
for example: www.telegraaf.nl/financieel/2130573762/woede-bij-winkels-die-nog-open-zijn

In source there is a script starting before the <title data-react-helmet="true"> tag, with the title. Short content starts then with <script data-react-helmet="true" type="application/ld+json"> tag, then the rest of the article which is behind the paywall starts at the tag ,"articleBody":",,

**Comment by magnolia1234** [comment]
Premium articles fixed in latest master zip-file.
While moving from a premium to a regular article you may encounter an error (also fixed by redirect).
Some weird tracking-referer is used which might conflict with BPC.

**Comment by mistere31** [comment]
Tested and works great! Thanks!
