### ISSUE TITLE
Irish Times - Request

### ISSUE THREAD

**Issue by severing77** [magnolia1234/bypass-paywalls-chrome-clean#78]
Hi! Thank you for all your effort!

Is it possible to remove the paywall for the Irish Times? 

https://www.irishtimes.com/opinion/coronavirus-has-created-an-opening-for-a-fairer-health-service-1.4213052?mode=sample&auth-failed=1&pw-origin=https%3A%2F%2Fwww.irishtimes.com%2Fopinion%2Fcoronavirus-has-created-an-opening-for-a-fairer-health-service-1.4213052

**Comment by magnolia1234** [comment]
Premium articles have a hard paywall (subscription-only).
In options it also says 'free artciles only'.
