### ISSUE TITLE
afr.com - images missing

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-chrome-clean#80]
Hi magnolia1234,

Images not displaying on https://www.afr.com/politics/federal/china-spree-sparks-firb-crackdown-20200329-p54exo

Tried both incognito and normal mode

Any clues?

**Comment by magnolia1234** [comment]
Images visible here, but maybe blocked by uBlock at your end?

**Comment by danielgruber8** [comment]
Disabling ublock origin worked, its weird as was working previously and I haven't added any other filter lists
Anyway I added afr.com to my whitelist so all good :)

**Comment by magnolia1234** [comment]
Maybe check MyFilters? ;-)
