### ISSUE TITLE
Barron's not working

### ISSUE THREAD

**Issue by inigma1** [magnolia1234/bypass-paywalls-chrome-clean#81]
I'm unable to read several articles on www.barrons.com. After an initial para, they ask to subscribe or sign in to read further. One of the articles is:

https://www.barrons.com/articles/dow-jones-industrial-average-ignores-coronavirus-for-one-week-it-wont-be-able-to-again-51585353765?mod=past_editions

I followed the troubleshooting tips (updating extension to latest version then using it with uBlock Origin, refreshing etc.) but it didn't work.

**Comment by magnolia1234** [comment]
Barron's combined articles can't be read (deconstructed), it seems.
Most of the separate articles/links are still available though (also without BPC).

**Comment by magnolia1234** [comment]
Just added fix for Barron's links to sign in/read more articles.
Like your article-link: sometimes article holds on to multiple recommendations layout (only intros).
Also bottom (recommendation) article-link stays unaltered (probably timing issue).

**Comment by inigma1** [comment]
Great, I think the fix works. In the multiple recommendations layout which requires to sign in/ subscribe to read an article, I clicked on a link to the section where it belongs (just on top of the article's title) and could access the complete thing from there. Thank you!!

**Comment by magnolia1234** [comment]
Still not working for all articles though.
Section works good for new articles.
You can also click on author, but sometimes not all articles show up there.

**Comment by inigma1** [comment]
Ok, no worries
