### ISSUE TITLE
Can't be used while browsing Quora

### ISSUE THREAD

**Issue by IBNU1** [magnolia1234/bypass-paywalls-chrome-clean#86]
When this extentenision is used while browsing Quora, it disables the search functionality and prevents you from expanding answers.

https://www.quora.com/

**Comment by magnolia1234** [comment]
Expanding answers works still fine for me, but indeed search not working with Googlebot-fix.
How many articles can you open on Quora with BPC disabled (still paywall?)?

**Comment by magnolia1234** [comment]
When you block Quora's cookies the answers won't expand (not needed in BPC).
I'll add a fix for the disabled search later.

**Comment by danielgruber8** [comment]
> I'll add a fix for the disabled search later.

You're an awesome and amazing web wizard. 
How unfortunate you don't do private work :( 
Are you based in Europe or USA?

**Comment by frantzkamus** [comment]
Same problem on my side

**Comment by magnolia1234** [comment]
Quora search fixed in latest master zip-file.

**Comment by magnolia1234** [comment]
> How unfortunate you don't do private work :(
> Are you based in Europe or USA?

@danielgruber8 
Sure, I'm familiar with your oftopic private work request ;-)
We're based in Europe.

**Comment by frantzkamus** [comment]
> We're based in Europe.

This is why our project includes many websites from many countries, unlike competing projects that are mainly focused on US newspapers ;-)
