### ISSUE TITLE
Request to add the site Foreign Affairs

### ISSUE THREAD

**Issue by rnzdnyr** [magnolia1234/bypass-paywalls-chrome-clean#88]
Could you please add the site Foreign Affairs (www.foreignaffairs.com)?

The link to the article is as follows:
https://www.foreignaffairs.com/articles/china/2020-02-06/digital-dictators

Thank you.

**Comment by magnolia1234** [comment]
Most articles on Foreign Affairs have a hard paywall (subscription-only).

**Comment by rnzdnyr** [comment]
I understand. Thank you anyways :)
