### ISSUE TITLE
Request to add the site Gestión

### ISSUE THREAD

**Issue by rnzdnyr** [magnolia1234/bypass-paywalls-chrome-clean#89]
Could you please add the site Gestión (gestion.pe)?

The link to the article is as follows:
https://gestion.pe/economia/hugo-santa-maria-hasta-la-semana-pasada-el-25-de-trabajadores-perdio-su-empleo-noticia/

Thank you.

**Comment by magnolia1234** [comment]
I'll add the site later, but for now you can add the domain to custom sites with block_javascript option enabled.

**Comment by magnolia1234** [comment]
Gestión.pe added and fixed menu for ElComercio.pe (only at main page & sections).

**Comment by danielgruber8** [comment]
This project always keeps getting better......

**Comment by magnolia1234** [comment]
> This project always keeps getting better......

You're also reading Peruvian newspapers now? ;-)

**Comment by rnzdnyr** [comment]
Thank you very much! And yes, this project only keeps getting better 🤗
