### ISSUE TITLE
new site, Kleine Zeitung please

### ISSUE THREAD

**Issue by jimmydeuxfois** [magnolia1234/bypass-paywalls-chrome-clean#9]
hi thank you for the Clean breakup 

this is one of best extensions

could you add https://www.kleinezeitung.at/politik/innenpolitik/5754426/Buch-als-Ausloeser_Fassmann-setzt-Susanne-Wiesinger-vor-die-Tuere

thanks for your efforts

**Comment by magnolia1234** [comment]
Looks like hard paywall (subscription-only).

**Comment by jimmydeuxfois** [comment]
this is too bad because I found an extension that works with Kleine Zeitung: https://github.com/rushilsrivastava/OpenNews are you sure this is hard paywall? thanks for you time replying

**Comment by magnolia1234** [comment]
OpenNews claims to support the site, but its not working either.
I've tested that extension before and a lot of sites weren't bypassed.

**Comment by jimmydeuxfois** [comment]
yes I have tests OpenNews on Kleine Zeitung and sometimes it works sometimes not (you must reinstall the extension, refresh, etc. until it works)

example: 
<img width="1022" alt="Screen Shot 2020-01-19 at 13 18 04" src="https://user-images.githubusercontent.com/56964267/72680801-560b4d80-3abe-11ea-9af9-c1bbdf46ccbe.png">

So maybe there may be a way to bypass it if you get opennews partial solution. I understand it may not be worth the effort though, thanks anyway for you work

**Comment by magnolia1234** [comment]
Too buggy extension then, but I'll take a look at the sourcecode once.

**Comment by jimmydeuxfois** [comment]
ok I will still use opennews extension for this site for the moment but if prefer your bypass extension since you give more websites in french and german for my use!

thank for your help i will wait

**Comment by magnolia1234** [comment]
Kleine Zeitung disables its paywall on articles when you set the referrer to Facebook (but also news.google.com).
OpenNews seems to randomly rotate between these 2 referrers and a 3rd google.com which isn't working. That's why the random success ;-)
I'll add Kleine Zeitung in a new commit.

**Comment by magnolia1234** [comment]
Fixed !

**Comment by iscreamcoke** [comment]
@magnolia1234 you should use the referrer-solution more often for "hard" paywalls, remember The Athletic  ;-)

**Comment by magnolia1234** [comment]
And a quicker way to test it (referer/header extension), but Googlebot also needs the referer set (testing with just an user-agent extension was not enough).
But still, it's an intended bypass of the sites (not enabled for all).

**Comment by iscreamcoke** [comment]
> And a quicker way to test it (referer/header extension)

[Referer Control](https://chrome.google.com/webstore/detail/referer-control/hnkcfpcejkafcihlgbojoidoihckciin?hl=en) is the only one I can think of for Chrome but it has some flaws

**Comment by magnolia1234** [comment]
I've been using [ModHeader](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj?hl=en) just now.
I've added 3 profiles which set RequestHeader referer to Google, Google News or Facebook.
Btw Google News isn't working on Kleine Zeitung either (just Facebook).
A 4th referer might be Twitter or url-shortener t.co
PS for Referer Control you really need a manual.

**Comment by magnolia1234** [comment]
Twitter/t.co works for Medium, but it didn't function consistently in BP (sometimes you had to refresh).

**Comment by jimmydeuxfois** [comment]
thank you it worked with new version master.zip
