### ISSUE TITLE
New site request: Le Monde Diplomatique - English Edition (mondediplo.com)

### ISSUE THREAD

**Issue by rnzdnyr** [magnolia1234/bypass-paywalls-chrome-clean#95]
Could you please add the site Le Monde Diplomatique - English Edition (mondediplo.com)?

The link to the article is as follows:
https://mondediplo.com/2020/04/11cities

Thanks :)

**Comment by magnolia1234** [comment]
Premium articles have a hard paywall (subscription-only).
