### ISSUE TITLE
New site request: El Observador (elobservador.com.uy)

### ISSUE THREAD

**Issue by rnzdnyr** [magnolia1234/bypass-paywalls-chrome-clean#97]
Could you please add the site El Observador (elobservador.com.uy)?

The link to the article is as follows:
https://www.elobservador.com.uy/nota/la-negociacion-con-apple-google-y-facebook-para-hacer-realidad-la-app-uruguaya-de-coronavirus-20204918480?fbclid=IwAR0F2nUuEHWFhzPUcYYFsIGRz2AZRIEm42giipXxTGVPePS-Z4sHlxvwu38

Thanks :)

**Comment by magnolia1234** [comment]
Premium articles have a hard paywall (subscription-only).
