### ISSUE TITLE
practiceupdate

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-chrome-clean#98]
This link works when searching on Google 
https://www.practiceupdate.com/content/oral-zinc-gluconate-and-topical-triclosan-for-hidradenitis-suppurativa/46764

But when I try applying the Googlebot fix in the Custom Sites, it gets blocked somehow:
As you were browsing PracticeUpdate, something about your browser made us think you were a bot.

**Comment by magnolia1234** [comment]
Probably hard paywall with this kind of protection.
Btw I can't access the article by Google search.
