### ISSUE TITLE
Unable to update extension with latest master (_config.yml)

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234/bypass-paywalls-chrome-clean#99]
Failed to load extension
File
~/Downloads/bypass-paywalls-chrome-clean-master
Error
Cannot load extension with file or directory name _config.yml. Filenames starting with "_" are reserved for use by the system.
Could not load manifest.

**Comment by magnolia1234** [comment]
File comes from GitHub Pages.
You can delete _config.yml locally.

**Comment by magnolia1234** [comment]
I've deleted the file for theme-configuration now.

**Comment by danielgruber8** [comment]
Works now - thanks :)
Hope you had a nice Easter / Passover

**Comment by danielgruber8** [comment]
Do you need to remove this _config.yml in the Firefox extension also?
Or is this problem specific to Chrome?

**Comment by magnolia1234** [comment]
Specific to Chrome indeed, but only used for setting a theme on GitHub pages.
